# Site settings
title: oracle-dba.ru

description: > # this means to ignore newlines until "baseurl:"
  Oracle, DBA, Linux, Weblogic, BI
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://oracle-dba.ru" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
